import { createContext, useContext, ReactNode, useState, useEffect } from "react";

type Language = "en" | "it";

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
};

export const LanguageContext = createContext<LanguageContextType | null>(null);

// Comprehensive translations for the application
const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    "app.name": "Trend",
    "app.tagline": "Financial Market Sentiment Tracker",
    
    // Navigation
    "nav.home": "Home",
    "nav.leaderboard": "Leaderboard",
    "nav.profile": "Profile",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.register": "Register",
    
    // Home page
    "home.welcome": "Welcome to Trend",
    "home.welcome_user": "Welcome, {username}",
    "home.subtitle": "Track and share sentiment on financial assets",
    "home.login_prompt": "to add your own ratings",
    "home.top_assets": "Top Assets",
    "home.trending_up": "Trending Up",
    "home.trending_down": "Trending Down",
    "home.search_placeholder": "Search assets...",
    "home.language_selector": "Language",
    "home.language_en": "English",
    "home.language_it": "Italian",
    "home.total_assets": "Total Assets",
    "home.how_it_works": "How Trend Works",
    "home.track_assets": "Track Assets",
    "home.track_description": "Follow stocks and cryptocurrencies and see real-time community sentiment.",
    "home.make_predictions": "Make Predictions",
    "home.predictions_description": "Add your own sentiment ratings and percentage predictions for assets.",
    "home.earn_badges": "Earn Badges",
    "home.badges_description": "Get rewarded for accurate predictions with monthly performance badges.",

    // Analyst consensus
    "analyst.header": "ANALYST CONSENSUS",
    "analyst.header_price": "ANALYST PRICE TARGET",
    "analyst.prompt": "See the Price Targets and Ratings of:",
    "analyst.duration": "Duration",
    "analyst.short": "Short",
    "analyst.medium": "Medium", 
    "analyst.long": "Long",
    "analyst.all": "All Analysts",
    "analyst.top": "Top Analysts",
    "analyst.buy": "BUY",
    "analyst.hold": "HOLD",
    "analyst.sell": "SELL",
    "analyst.up_predictions": "UP PREDICTIONS",
    "analyst.down_predictions": "DOWN PREDICTIONS",
    "analyst.recommendation.disclaimer": "Based on recommendations offered by {count} analysts for {symbol} in the last 3 months, the general consensus is",
    "analyst.based_on": "Based on {count} classified analysts",
    "analyst.last_12": "Last 12 Months",
    "analyst.next_12": "Next 12 Months",
    "analyst.low_estimate": "LOW ESTIMATE",
    "analyst.avg_target": "AVERAGE PRICE TARGET",
    "analyst.high_estimate": "HIGH ESTIMATE",
    "analyst.error_consensus": "Failed to load analyst consensus data",
    "analyst.error_price": "Failed to load price target data",
    "analyst.no_consensus": "No analyst data available",
    "analyst.no_price": "No price target data available",

    // Global sentiment
    "global.title": "Global App Sentiment",
    "global.description": "Community prediction balance across all assets",
    "global.period_rules": "Periods: Short (Mon-Sun CEST) • Medium (Month CEST) • Long (Quarter CEST)",
    "global.duration": "Duration",
    "global.period": "Period",
    "global.now": "Now",
    "global.up": "Up",
    "global.down": "Down",
    "global.top_down": "Top Down ({count})",
    "global.top_up": "Top Up ({count})",
    "global.asset": "Asset",
    "global.votes": "Votes",
    "global.share": "Share",
    "global.no_data": "No data",
    "global.short": "Short",
    "global.medium": "Medium",
    "global.long": "Long",

    // Search
    "search.title": "Search Assets",
    "search.description": "Find assets by name, symbol, or type",
    
    // Language
    "language.title": "Language Settings",
    "language.description": "Choose your preferred language",
    
    // Sentiment
    "sentiment.positive": "Positive",
    "sentiment.neutral": "Neutral",
    "sentiment.negative": "Negative",
    "sentiment.top_positive": "Top Positive Assets",
    "sentiment.top_negative": "Top Negative Assets",
    "sentiment.bullish": "Assets with the most bullish sentiment",
    "sentiment.bearish": "Assets with the most bearish sentiment",
    "sentiment.no_positive": "No positive assets found",
    "sentiment.no_negative": "No negative assets found",
    
    // Asset types
    "asset.type.stock": "Stock",
    "asset.type.cryptocurrency": "Cryptocurrency",
    "asset.crypto_title": "Cryptocurrency Assets",
    "asset.stock_title": "Stock Assets",
    "asset.forex_title": "Forex Pairs",
    "asset.no_crypto": "No cryptocurrency assets found.",
    "asset.no_stock": "No stock assets found.",
    "asset.no_forex": "No forex pairs available.",
    "asset.suggest": "Suggest Asset",
    "asset.suggest_title": "Suggest a New Asset",
    "asset.suggest_description": "Don't see your favorite stock or cryptocurrency? Suggest it here and we'll add it to our database.",
    
    // Auth
    "auth.signin": "Sign in",
    "auth.login": "Log in",
    "auth.register": "Register",
    
    // Profile
    "profile.title": "Profile",
    "profile.predictions": "Predictions",
    "profile.verification": "Verification Status",
    "profile.verification_progress": "Verification Progress",
    
    // Action buttons
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.submit": "Submit",
    
    // Share
    "share.share_app": "Share App",
    "share.share_with_friends": "Share with friends",
    "share.invite_friends": "Invite your friends to try Trend and track market sentiments together",
    "share.copied": "Copied!",
    "share.link_copied": "Link copied to clipboard",
    "share.or_share_link": "Or copy this link",
    "share.homepage": "Homepage",
    "share.leaderboard": "Leaderboard",
    "share.message": "Check out Trend, a platform for tracking financial market sentiments!",
    "share.email_subject": "Join me on Trend - Financial Market Sentiment Tracker",
    
    // Email verification
    "email_verification.status_label": "Status:",
    "email_verification.verified": "Verified",
    "email_verification.unverified": "Not Verified",
    "email_verification.verified_title": "Email Verified",
    "email_verification.verified_desc": "Your email address has been successfully verified.",
    "email_verification.unverified_title": "Email Not Verified",
    "email_verification.unverified_desc": "Please verify your email to unlock verified advisor status. Check your inbox for a verification email or request a new one.",
    "email_verification.resend_button": "Resend Verification Email",
    "email_verification.sending": "Sending...",
    "email_verification.resend_success_title": "Verification Email Sent",
    "email_verification.resend_success_desc": "Please check your inbox and click the verification link.",
    "email_verification.resend_error_title": "Failed to Send Email",
    "email_verification.cooldown_message": "Please wait {minutes} minutes before requesting another verification email",
    "email_verification.email_changed": "Email changed successfully. Please check your new email for verification.",
    "email_verification.change_email_title": "Change Email Address",
    "email_verification.new_email_label": "New Email Address",
    "email_verification.current_password_label": "Current Password",
    "email_verification.change_email_button": "Change Email",
    "email_verification.change_email_success": "Email changed successfully",
    "email_verification.change_email_error": "Failed to change email",
    
    // Badges
    "badges.title": "Achievement Badges",
    "badges.description": "Your monthly performance recognition",
    "badges.current": "Current Badge",
    "badges.history": "Badge History",
    "badges.noBadges": "You don't have any badges yet. Keep making predictions to earn badges!",
    "badges.noCurrentBadge": "No current badge. You need to be in the top 5 predictors last month to earn a badge.",
    "badges.noBadgeHistory": "No badge history available.",
    "badges.currentDescription": "Your current badge for last month's performance",
    "badges.top1": "Diamond Predictor",
    "badges.top2": "Platinum Predictor",
    "badges.top3": "Gold Predictor",
    "badges.top4": "Silver Predictor",
    "badges.top5": "Bronze Predictor",
    "badges.unknownBadge": "Mystery Badge",
    "badges.accuracy": "Accuracy: {value}%",
    "badges.predictions": "Predictions: {count}",
    "badges.viewHistory": "View Badge History",
    
    // Admin Panel
    "admin.dashboard": "Admin Dashboard",
    "admin.description": "Manage assets, users, and system settings",
    "admin.assets_tab": "Asset Management",
    "admin.users_tab": "User Management",
    "admin.userlist_tab": "User List",
    "admin.refresh_data": "Refresh Data",
    "admin.assets.title": "Assets",
    "admin.assets.description": "Manage the assets available on the platform",
    "admin.assets.add": "Add Asset",
    "admin.assets.add_title": "Add New Asset",
    "admin.assets.add_description": "Enter the details for the new asset to add to the platform",
    "admin.assets.filter": "Filter by type",
    "admin.assets.search": "Search assets...",
    "admin.assets.no_assets": "No assets found matching your filters.",
    "admin.assets.showing": "Showing {filtered} of {total} assets",
    "admin.assets.name": "Name",
    "admin.assets.symbol": "Symbol",
    "admin.assets.type": "Type",
    "admin.assets.sentiment": "Sentiment",
    "admin.assets.prediction": "Prediction",
    "admin.assets.actions": "Actions",
    "admin.assets.delete_confirm": "Are you sure?",
    "admin.assets.delete_description": "This will permanently remove {name} ({symbol}) from the platform. This action cannot be undone.",
    "admin.users.title": "Users",
    "admin.users.description": "Manage user accounts and verification status",
    "admin.users.filter_all": "All Users",
    "admin.users.filter_verified": "Verified Users",
    "admin.users.filter_unverified": "Unverified Users",
    "admin.users.search": "Search users...",
    "admin.users.no_users": "No users found matching your filters.",
    "admin.users.showing": "Showing {filtered} of {total} users",
    "admin.users.verify": "Verify",
    "admin.users.unverify": "Cancel Verification",
    "admin.userlist.title": "Complete User List",
    "admin.userlist.description": "Detailed view of all registered users",
    "admin.userlist.refresh": "Refresh",
    "admin.userlist.username": "Username",
    "admin.userlist.email": "Email",
    "admin.userlist.registered": "Registered",
    "admin.userlist.predictions": "Predictions",
    "admin.userlist.accuracy": "Accuracy",
    "admin.userlist.badge": "Badge",
    "admin.userlist.verified": "Verified",
    "admin.userlist.not_verified": "Not Verified",
    "admin.userlist.none": "None",
    
    // Leaderboard
    "leaderboard.title": "Leaderboard",
    "leaderboard.include_admins": "Include Admins",
    "leaderboard.exclude_admins": "Exclude Admins",
    "leaderboard.all_users": "All Users",
    "leaderboard.regular_users_only": "Regular Users Only",
    "leaderboard.loading": "Loading...",
    "leaderboard.fetching": "Fetching leaderboard data...",
    "leaderboard.rank": "Rank",
    "leaderboard.username": "Username",
    "leaderboard.score": "Score",
    "leaderboard.predictions": "Predictions",
    "leaderboard.accuracy": "Accuracy",
    
    // User Profile
    "user_profile.title": "User Profile",
    "user_profile.joined": "Joined",
    "user_profile.email_verified": "Email Verified",
    "user_profile.admin": "Admin",
    "user_profile.bio": "Bio",
    "user_profile.monthly_score": "Monthly Score",
    "user_profile.total_score": "Total Score",
    "user_profile.last_month_rank": "Last month: Rank #{rank}",
    "user_profile.no_previous_rank": "No previous rank",
    "user_profile.followers": "Followers",
    "user_profile.following": "Following",
    "user_profile.achievements": "Achievements",
    "user_profile.overview": "Overview",
    "user_profile.predictions": "Predictions",
    "user_profile.history": "History",
    "user_profile.total_predictions": "Total Predictions",
    "user_profile.correct_predictions": "Correct Predictions",
    "user_profile.accuracy": "Accuracy",
    "user_profile.active_predictions": "Active Predictions",
    "user_profile.currently_active": "Currently active",
    "user_profile.follow_to_view": "Follow to view predictions",
    "user_profile.predictions_private": "Predictions are private",
    "user_profile.follow_to_view_history": "Follow this user to view their prediction history",
    "user_profile.no_predictions": "No predictions found",
    "user_profile.monthly_performance": "Monthly Performance",
    "user_profile.no_history": "No historical data available",
    "user_profile.not_found": "User Not Found",
    "user_profile.not_found_desc": "The user you're looking for doesn't exist.",
    
    // Sidebar
    "sidebar.overview": "Overview",
    "sidebar.chart": "Chart",
    "sidebar.leaderboard": "Leaderboard",
    "sidebar.profile": "Profile",
    "sidebar.logout": "Logout",
    "sidebar.search_placeholder": "Search Bitcoin, Ethereum...",
    "sidebar.search_placeholder_stock": "Search Apple, Tesla...",
    "sidebar.search_placeholder_forex": "Search EUR/USD, GBP/USD...",
    "sidebar.cryptocurrency": "Cryptocurrency",
    "sidebar.stocks": "Stocks",
    "sidebar.forex": "Forex",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.unknown_date": "Unknown date",
    "common.points_short": "pts",
    "common.slot": "Slot",
    "common.created": "Created",
    "common.back": "Back",
    
    // Prediction Status
    "prediction.status.active": "Active",
    "prediction.status.expired": "Expired",
    "prediction.status.evaluated": "Evaluated",
    "prediction.result.correct": "Correct",
    "prediction.result.incorrect": "Incorrect",
    "prediction.result.pending": "Pending",
    
    // Chart Page
    "chart.title": "Trading Chart",
    
    // Auth Page
    "auth.title": "Welcome to Trend",
    "auth.subtitle": "Financial Market Sentiment Tracker",
    "auth.login_tab": "Login",
    "auth.register_tab": "Register",
    "auth.email_label": "Email",
    "auth.email_placeholder": "Enter your email",
    "auth.password_label": "Password",
    "auth.password_placeholder": "Enter your password",
    "auth.username_label": "Username",
    "auth.username_placeholder": "Choose a username",
    "auth.confirm_password_label": "Confirm Password",
    "auth.confirm_password_placeholder": "Confirm your password",
    "auth.referral_code_label": "Referral Code (Optional)",
    "auth.referral_code_placeholder": "Enter referral code",
    "auth.login_button": "Login",
    "auth.register_button": "Create Account",
    "auth.google_signin": "Continue with Google",
    "auth.forgot_password": "Forgot Password?",
    "auth.reset_password": "Reset Password",
    "auth.send_reset_link": "Send Reset Link",
    "auth.back_to_login": "Back to Login",
    "auth.reset_requested": "Password reset link sent to your email",
    "auth.enter_new_password": "Enter New Password",
    "auth.reset_token_label": "Reset Token",
    "auth.new_password_label": "New Password",
    "auth.update_password": "Update Password",
    "auth.no_account": "Don't have an account?",
    "auth.have_account": "Already have an account?",
    "auth.sign_up": "Sign up",
    "auth.sign_in": "Sign in",
    
    // Profile Page
    "profile.my_profile": "My Profile",
    "profile.edit_profile": "Edit Profile",
    "profile.change_password": "Change Password",
    "profile.change_email": "Change Email",
    "profile.statistics": "Statistics",
    "profile.overview": "Overview",
    "profile.predictions": "Predictions",
    "profile.badges": "Badges",
    "profile.following": "Following",
    "profile.followers": "Followers",
    "profile.total_predictions": "Total Predictions",
    "profile.active_predictions": "Active",
    "profile.correct_predictions": "Correct",
    "profile.accuracy": "Accuracy",
    "profile.joined": "Joined",
    "profile.bio": "Bio",
    "profile.email": "Email",
    "profile.username": "Username",
    "profile.monthly_score": "Monthly Score",
    "profile.total_score": "Total Score",
    "profile.rank": "Rank",
    "profile.view_all": "View All",
    "profile.no_predictions": "No predictions yet",
    "profile.no_badges": "No badges yet",
    "profile.no_followers": "No followers yet",
    "profile.no_following": "Not following anyone yet",
    "profile.prediction_history": "Prediction History",
    "profile.asset": "Asset",
    "profile.direction": "Direction",
    "profile.duration": "Duration",
    "profile.status": "Status",
    "profile.result": "Result",
    "profile.points": "Points",
    "profile.created_at": "Created At",
    "profile.email_verified": "Email Verified",
    "profile.email_not_verified": "Email Not Verified",
    "profile.no_bio": "No bio available.",
    "profile.prediction_accuracy": "Prediction Accuracy",
    "profile.correct_out_of": "{correct} correct out of {total}",
    "profile.last_month_rank": "Last Month Rank",
    "profile.social": "Social",
    "profile.account": "Account",
    "profile.achievement_badges": "Achievement Badges",
    "profile.latest_activity": "Latest Activity",
    "profile.all": "All",
    "profile.evaluated": "Evaluated",
    "profile.coin": "Coin",
    "profile.date": "Date",
  },
  it: {
    // General
    "app.name": "Trend",
    "app.tagline": "Tracciatore di Sentimento del Mercato Finanziario",
    
    // Navigation
    "nav.home": "Home",
    "nav.leaderboard": "Classifica",
    "nav.profile": "Profilo",
    "nav.login": "Accedi",
    "nav.logout": "Esci",
    "nav.register": "Registrati",
    
    // Home page
    "home.welcome": "Benvenuto su Trend",
    "home.welcome_user": "Benvenuto, {username}",
    "home.subtitle": "Monitora e condividi il sentimento sugli asset finanziari",
    "home.login_prompt": "per aggiungere le tue valutazioni",
    "home.top_assets": "Asset Principali",
    "home.trending_up": "Tendenza Positiva",
    "home.trending_down": "Tendenza Negativa",
    "home.search_placeholder": "Cerca asset...",
    "home.language_selector": "Lingua",
    "home.language_en": "Inglese",
    "home.language_it": "Italiano",
    "home.total_assets": "Asset Totali",
    "home.how_it_works": "Come Funziona Trend",
    "home.track_assets": "Monitora Asset",
    "home.track_description": "Segui azioni e criptovalute e visualizza il sentiment della comunità in tempo reale.",
    "home.make_predictions": "Fai Previsioni",
    "home.predictions_description": "Aggiungi le tue valutazioni e previsioni percentuali per gli asset.",
    "home.earn_badges": "Ottieni Badge",
    "home.badges_description": "Vieni premiato per previsioni accurate con badge di performance mensili.",

    // Analyst consensus
    "analyst.header": "CONSENSO DELL'ANALISTA",
    "analyst.header_price": "OBIETTIVO DI PREZZO DELL'ANALISTA",
    "analyst.prompt": "Vedi gli obiettivi di prezzo e le valutazioni di:",
    "analyst.duration": "Durata",
    "analyst.short": "Breve",
    "analyst.medium": "Medio",
    "analyst.long": "Lungo",
    "analyst.all": "Tutti gli Analisti",
    "analyst.top": "Analisti Top",
    "analyst.buy": "ACQUISTA",
    "analyst.hold": "ATTENDI",
    "analyst.sell": "VENDI",
    "analyst.up_predictions": "PREVISIONI AL RIALZO",
    "analyst.down_predictions": "PREVISIONI AL RIBASSO",
    "analyst.recommendation.disclaimer": "Basato sulle raccomandazioni offerte da {count} analisti per {symbol} negli ultimi 3 mesi, il consenso generale è",
    "analyst.based_on": "Basato su {count} analisti classificati",
    "analyst.last_12": "Ultimi 12 Mesi",
    "analyst.next_12": "Prossimi 12 Mesi",
    "analyst.low_estimate": "STIMA BASSA",
    "analyst.avg_target": "OBIETTIVO PREZZO MEDIO",
    "analyst.high_estimate": "STIMA ALTA",
    "analyst.error_consensus": "Impossibile caricare i dati del consenso degli analisti",
    "analyst.error_price": "Impossibile caricare i dati del target di prezzo",
    "analyst.no_consensus": "Nessun dato analista disponibile",
    "analyst.no_price": "Nessun dato obiettivo di prezzo disponibile",

    // Global sentiment
    "global.title": "Sentiment Globale dell'App",
    "global.description": "Bilanciamento delle previsioni della community su tutti gli asset",
    "global.period_rules": "Periodi: Breve (Lun-Dom CEST) • Medio (Mese CEST) • Lungo (Trimestre CEST)",
    "global.duration": "Durata",
    "global.period": "Periodo",
    "global.now": "Ora",
    "global.up": "Su",
    "global.down": "Giù",
    "global.top_down": "Top Down ({count})",
    "global.top_up": "Top Up ({count})",
    "global.asset": "Asset",
    "global.votes": "Voti",
    "global.share": "Quota",
    "global.no_data": "Nessun dato",
    "global.short": "Breve",
    "global.medium": "Medio",
    "global.long": "Lungo",

    // Search
    "search.title": "Cerca Asset",
    "search.description": "Trova asset per nome, simbolo o tipo",
    
    // Language
    "language.title": "Impostazioni Lingua",
    "language.description": "Scegli la tua lingua preferita",
    
    // Sentiment
    "sentiment.positive": "Positivo",
    "sentiment.neutral": "Neutro",
    "sentiment.negative": "Negativo",
    "sentiment.top_positive": "Asset Più Positivi",
    "sentiment.top_negative": "Asset Più Negativi",
    "sentiment.bullish": "Asset con il sentimento più rialzista",
    "sentiment.bearish": "Asset con il sentimento più ribassista",
    "sentiment.no_positive": "Nessun asset positivo trovato",
    "sentiment.no_negative": "Nessun asset negativo trovato",
    
    // Asset types
    "asset.type.stock": "Azione",
    "asset.type.cryptocurrency": "Criptovaluta",
    "asset.crypto_title": "Asset Criptovalute",
    "asset.stock_title": "Asset Azioni",
    "asset.forex_title": "Coppie Forex",
    "asset.no_crypto": "Nessuna criptovaluta trovata.",
    "asset.no_stock": "Nessuna azione trovata.",
    "asset.no_forex": "Nessuna coppia forex disponibile.",
    "asset.suggest": "Suggerisci Asset",
    "asset.suggest_title": "Suggerisci un Nuovo Asset",
    "asset.suggest_description": "Non vedi la tua azione o criptovaluta preferita? Suggeriscila qui e la aggiungeremo al nostro database.",
    
    // Auth
    "auth.signin": "Accedi",
    "auth.login": "Accedi",
    "auth.register": "Registrati",
    
    // Profile
    "profile.title": "Profilo",
    "profile.predictions": "Previsioni",
    "profile.verification": "Stato di Verifica",
    "profile.verification_progress": "Progresso di Verifica",
    
    // Action buttons
    "action.save": "Salva",
    "action.cancel": "Annulla",
    "action.submit": "Invia",
    
    // Share
    "share.share_app": "Condividi App",
    "share.share_with_friends": "Condividi con amici",
    "share.invite_friends": "Invita i tuoi amici a provare Trend e monitorare insieme i sentiment del mercato",
    "share.copied": "Copiato!",
    "share.link_copied": "Link copiato negli appunti",
    "share.or_share_link": "Oppure copia questo link",
    "share.homepage": "Homepage",
    "share.leaderboard": "Classifica",
    "share.message": "Prova Trend, una piattaforma per monitorare il sentiment dei mercati finanziari!",
    "share.email_subject": "Unisciti a me su Trend - Monitoraggio del Sentiment del Mercato Finanziario",
    
    // Email verification
    "email_verification.status_label": "Stato:",
    "email_verification.verified": "Verificata",
    "email_verification.unverified": "Non Verificata",
    "email_verification.verified_title": "Email Verificata",
    "email_verification.verified_desc": "Il tuo indirizzo email è stato verificato con successo.",
    "email_verification.unverified_title": "Email Non Verificata",
    "email_verification.unverified_desc": "Verifica la tua email per sbloccare lo stato di consulente verificato. Controlla la tua casella di posta o richiedi una nuova email di verifica.",
    "email_verification.resend_button": "Reinvia Email di Verifica",
    "email_verification.sending": "Invio in corso...",
    "email_verification.resend_success_title": "Email di Verifica Inviata",
    "email_verification.resend_success_desc": "Controlla la tua casella di posta e clicca sul link di verifica.",
    "email_verification.resend_error_title": "Invio Email Fallito",
    "email_verification.cooldown_message": "Aspetta {minutes} minuti prima di richiedere un'altra email di verifica",
    "email_verification.email_changed": "Email cambiata con successo. Controlla la tua nuova email per la verifica.",
    "email_verification.change_email_title": "Cambia Indirizzo Email",
    "email_verification.new_email_label": "Nuovo Indirizzo Email",
    "email_verification.current_password_label": "Password Attuale",
    "email_verification.change_email_button": "Cambia Email",
    "email_verification.change_email_success": "Email cambiata con successo",
    "email_verification.change_email_error": "Impossibile cambiare email",
    
    // Badges
    "badges.title": "Badge di Rendimento",
    "badges.description": "Riconoscimenti per le tue performance mensili",
    "badges.current": "Badge Attuale",
    "badges.history": "Storico Badge",
    "badges.noBadges": "Non hai ancora badge. Continua a fare previsioni per guadagnare badge!",
    "badges.noCurrentBadge": "Nessun badge attuale. Devi essere tra i primi 5 predittori del mese scorso per guadagnare un badge.",
    "badges.noBadgeHistory": "Nessuna cronologia badge disponibile.",
    "badges.currentDescription": "Il tuo badge attuale per le performance del mese scorso",
    "badges.top1": "Predittore Diamante",
    "badges.top2": "Predittore Platino",
    "badges.top3": "Predittore Oro",
    "badges.top4": "Predittore Argento",
    "badges.top5": "Predittore Bronzo",
    "badges.unknownBadge": "Badge Misterioso",
    "badges.accuracy": "Precisione: {value}%",
    "badges.predictions": "Previsioni: {count}",
    "badges.viewHistory": "Visualizza Storico Badge",
    
    // Admin Panel
    "admin.dashboard": "Pannello Amministratore",
    "admin.description": "Gestisci asset, utenti e impostazioni di sistema",
    "admin.assets_tab": "Gestione Asset",
    "admin.users_tab": "Gestione Utenti",
    "admin.userlist_tab": "Elenco Utenti",
    "admin.refresh_data": "Aggiorna Dati",
    "admin.assets.title": "Asset",
    "admin.assets.description": "Gestisci gli asset disponibili sulla piattaforma",
    "admin.assets.add": "Aggiungi Asset",
    "admin.assets.add_title": "Aggiungi Nuovo Asset",
    "admin.assets.add_description": "Inserisci i dettagli per il nuovo asset da aggiungere alla piattaforma",
    "admin.assets.filter": "Filtra per tipo",
    "admin.assets.search": "Cerca asset...",
    "admin.assets.no_assets": "Nessun asset trovato corrispondente ai filtri.",
    "admin.assets.showing": "Visualizzando {filtered} di {total} asset",
    "admin.assets.name": "Nome",
    "admin.assets.symbol": "Simbolo",
    "admin.assets.type": "Tipo",
    "admin.assets.sentiment": "Sentiment",
    "admin.assets.prediction": "Previsione",
    "admin.assets.actions": "Azioni",
    "admin.assets.delete_confirm": "Sei sicuro?",
    "admin.assets.delete_description": "Questo rimuoverà permanentemente {name} ({symbol}) dalla piattaforma. Questa azione non può essere annullata.",
    "admin.users.title": "Utenti",
    "admin.users.description": "Gestisci account utente e stato di verifica",
    "admin.users.filter_all": "Tutti gli Utenti",
    "admin.users.filter_verified": "Utenti Verificati",
    "admin.users.filter_unverified": "Utenti Non Verificati",
    "admin.users.search": "Cerca utenti...",
    "admin.users.no_users": "Nessun utente trovato corrispondente ai filtri.",
    "admin.users.showing": "Visualizzando {filtered} di {total} utenti",
    "admin.users.verify": "Verifica",
    "admin.users.unverify": "Annulla Verifica",
    "admin.userlist.title": "Elenco completo degli utenti",
    "admin.userlist.description": "Visualizzazione dettagliata di tutti gli utenti registrati",
    "admin.userlist.refresh": "Aggiorna",
    "admin.userlist.username": "Nome Utente",
    "admin.userlist.email": "Email",
    "admin.userlist.registered": "Registrato",
    "admin.userlist.predictions": "Previsioni",
    "admin.userlist.accuracy": "Precisione",
    "admin.userlist.badge": "Badge",
    "admin.userlist.verified": "Verificato",
    "admin.userlist.not_verified": "Non Verificato",
    "admin.userlist.none": "Nessuno",
    
    // Leaderboard
    "leaderboard.title": "Classifica",
    "leaderboard.include_admins": "Includi Amministratori",
    "leaderboard.exclude_admins": "Escludi Amministratori",
    "leaderboard.all_users": "Tutti gli Utenti",
    "leaderboard.regular_users_only": "Solo Utenti Normali",
    "leaderboard.loading": "Caricamento...",
    "leaderboard.fetching": "Recupero dati classifica...",
    "leaderboard.rank": "Posizione",
    "leaderboard.username": "Nome Utente",
    "leaderboard.score": "Punteggio",
    "leaderboard.predictions": "Previsioni",
    "leaderboard.accuracy": "Precisione",
    
    // User Profile
    "user_profile.title": "Profilo Utente",
    "user_profile.joined": "Iscritto",
    "user_profile.email_verified": "Email Verificata",
    "user_profile.admin": "Amministratore",
    "user_profile.bio": "Bio",
    "user_profile.monthly_score": "Punteggio Mensile",
    "user_profile.total_score": "Punteggio Totale",
    "user_profile.last_month_rank": "Mese scorso: Posizione #{rank}",
    "user_profile.no_previous_rank": "Nessuna posizione precedente",
    "user_profile.followers": "Seguaci",
    "user_profile.following": "Seguiti",
    "user_profile.achievements": "Risultati",
    "user_profile.overview": "Panoramica",
    "user_profile.predictions": "Previsioni",
    "user_profile.history": "Storico",
    "user_profile.total_predictions": "Previsioni Totali",
    "user_profile.correct_predictions": "Previsioni Corrette",
    "user_profile.accuracy": "Precisione",
    "user_profile.active_predictions": "Previsioni Attive",
    "user_profile.currently_active": "Attualmente attive",
    "user_profile.follow_to_view": "Segui per visualizzare le previsioni",
    "user_profile.predictions_private": "Le previsioni sono private",
    "user_profile.follow_to_view_history": "Segui questo utente per visualizzare lo storico delle previsioni",
    "user_profile.no_predictions": "Nessuna previsione trovata",
    "user_profile.monthly_performance": "Performance Mensile",
    "user_profile.no_history": "Nessun dato storico disponibile",
    "user_profile.not_found": "Utente Non Trovato",
    "user_profile.not_found_desc": "L'utente che stai cercando non esiste.",
    
    // Sidebar
    "sidebar.overview": "Panoramica",
    "sidebar.chart": "Grafico",
    "sidebar.leaderboard": "Classifica",
    "sidebar.profile": "Profilo",
    "sidebar.logout": "Esci",
    "sidebar.search_placeholder": "Cerca Bitcoin, Ethereum...",
    "sidebar.search_placeholder_stock": "Cerca Apple, Tesla...",
    "sidebar.search_placeholder_forex": "Cerca EUR/USD, GBP/USD...",
    "sidebar.cryptocurrency": "Criptovaluta",
    "sidebar.stocks": "Azioni",
    "sidebar.forex": "Forex",
    
    // Common
    "common.loading": "Caricamento...",
    "common.error": "Errore",
    "common.unknown_date": "Data sconosciuta",
    "common.points_short": "pt",
    "common.slot": "Slot",
    "common.created": "Creato",
    "common.back": "Indietro",
    
    // Prediction Status
    "prediction.status.active": "Attivo",
    "prediction.status.expired": "Scaduto",
    "prediction.status.evaluated": "Valutato",
    "prediction.result.correct": "Corretto",
    "prediction.result.incorrect": "Errato",
    "prediction.result.pending": "In sospeso",
    
    // Chart Page
    "chart.title": "Grafico di Trading",
    
    // Auth Page
    "auth.title": "Benvenuto su Trend",
    "auth.subtitle": "Tracker del Sentimento del Mercato Finanziario",
    "auth.login_tab": "Accedi",
    "auth.register_tab": "Registrati",
    "auth.email_label": "Email",
    "auth.email_placeholder": "Inserisci la tua email",
    "auth.password_label": "Password",
    "auth.password_placeholder": "Inserisci la tua password",
    "auth.username_label": "Nome utente",
    "auth.username_placeholder": "Scegli un nome utente",
    "auth.confirm_password_label": "Conferma Password",
    "auth.confirm_password_placeholder": "Conferma la tua password",
    "auth.referral_code_label": "Codice Referral (Facoltativo)",
    "auth.referral_code_placeholder": "Inserisci codice referral",
    "auth.login_button": "Accedi",
    "auth.register_button": "Crea Account",
    "auth.google_signin": "Continua con Google",
    "auth.forgot_password": "Password Dimenticata?",
    "auth.reset_password": "Reimposta Password",
    "auth.send_reset_link": "Invia Link di Ripristino",
    "auth.back_to_login": "Torna al Login",
    "auth.reset_requested": "Link di ripristino password inviato alla tua email",
    "auth.enter_new_password": "Inserisci Nuova Password",
    "auth.reset_token_label": "Token di Ripristino",
    "auth.new_password_label": "Nuova Password",
    "auth.update_password": "Aggiorna Password",
    "auth.no_account": "Non hai un account?",
    "auth.have_account": "Hai già un account?",
    "auth.sign_up": "Registrati",
    "auth.sign_in": "Accedi",
    
    // Profile Page
    "profile.my_profile": "Il Mio Profilo",
    "profile.edit_profile": "Modifica Profilo",
    "profile.change_password": "Cambia Password",
    "profile.change_email": "Cambia Email",
    "profile.statistics": "Statistiche",
    "profile.overview": "Panoramica",
    "profile.predictions": "Previsioni",
    "profile.badges": "Badge",
    "profile.following": "Seguiti",
    "profile.followers": "Follower",
    "profile.total_predictions": "Previsioni Totali",
    "profile.active_predictions": "Attive",
    "profile.correct_predictions": "Corrette",
    "profile.accuracy": "Precisione",
    "profile.joined": "Iscritto",
    "profile.bio": "Biografia",
    "profile.email": "Email",
    "profile.username": "Nome utente",
    "profile.monthly_score": "Punteggio Mensile",
    "profile.total_score": "Punteggio Totale",
    "profile.rank": "Classifica",
    "profile.view_all": "Vedi Tutto",
    "profile.no_predictions": "Nessuna previsione ancora",
    "profile.no_badges": "Nessun badge ancora",
    "profile.no_followers": "Nessun follower ancora",
    "profile.no_following": "Non segui ancora nessuno",
    "profile.prediction_history": "Cronologia Previsioni",
    "profile.asset": "Asset",
    "profile.direction": "Direzione",
    "profile.duration": "Durata",
    "profile.status": "Stato",
    "profile.result": "Risultato",
    "profile.points": "Punti",
    "profile.created_at": "Creato il",
    "profile.email_verified": "Email Verificata",
    "profile.email_not_verified": "Email Non Verificata",
    "profile.no_bio": "Nessuna biografia disponibile.",
    "profile.prediction_accuracy": "Precisione Previsioni",
    "profile.correct_out_of": "{correct} corrette su {total}",
    "profile.last_month_rank": "Classifica Mese Scorso",
    "profile.social": "Social",
    "profile.account": "Account",
    "profile.achievement_badges": "Badge Risultati",
    "profile.latest_activity": "Attività Recente",
    "profile.all": "Tutti",
    "profile.evaluated": "Valutate",
    "profile.coin": "Moneta",
    "profile.date": "Data",
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Try to get saved language from localStorage
    const savedLanguage = localStorage.getItem("language") as Language;
    return savedLanguage || "en";
  });

  // Function to translate keys with parameter replacements
  const t = (key: string, params?: Record<string, string | number>): string => {
    let translated = translations[language][key] || key;
    
    // Replace parameters if provided
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translated = translated.replace(`{${paramKey}}`, String(paramValue));
      });
    }
    
    return translated;
  };

  // Update localStorage when language changes
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

  // Initial localStorage setup
  useEffect(() => {
    localStorage.setItem("language", language);
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}